services:
  url-shortener-db:
    image: mysql:8.4
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: url_shortener_db
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -p\"$$MYSQL_ROOT_PASSWORD\""]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 20s

  redis:
    image: redis:7.4-alpine
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 10

  backend:
    build:
      context: ./backend/url-shortener
      dockerfile: indiedev
    expose:
      - "8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://url-shortener-db:3306/url_shortener_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      SPRING_DATA_REDIS_HOST: redis
    depends_on:
      url-shortener-db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend/url-shortener-ui
      dockerfile: dockerfile
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_started
    restart: unless-stopped

volumes:
  mysql-data:
