server.port=8080
server.servlet.context-path=/

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/url_shortener_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:rohit}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

spring.application.name=url-shortener


# Enable Flyway
spring.flyway.enabled=true
# Baseline the existing database (created by Hibernate)
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=1

# For database logging
# Log the actual values bound to SQL parameters (?)
logging.level.org.hibernate.orm.jdbc.bind=trace

# Log the SQL execution structural details and results
logging.level.org.hibernate.SQL=debug

spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}
